---
sudo: required

branches:
  only:
  - main # Branch from which to publish

services:
  - docker

before_install:
  - mkdir -p output
  - docker pull pandoc/core

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name pandoc -t revealjs -s --self-contained slides/SLIDES -V slideNumber=true -o output/index.html -V theme=solarized

after_error:
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  local_dir: output
  on:
    branch: main
