---
before_install:
  # Install pandoc
  - sudo apt-get update
  - sudo apt-get -y install pandoc
  - pandoc --version

script:
  # create docs directory for pandoc output
  - mkdir docs
  - git clone https://github.com/hakimel/reveal.js.git docs
  # Generate reveal.js powered HTML from Markdown
  - pandoc -t revealjs -s --self-contained slides/SLIDES -V slideNumber=true -o docs/index.html -V theme=solarized

# Deploy to GitHub pages (see https://docs.travis-ci.com/user/deployment/pages/)
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
