---
sudo: required

branches:
  only:
  - main # Branch from which to publish

services:
  - docker

before_install:
  - mkdir -p output
  - curl -L https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb > pandoc.deb
  - dpkg -i pandoc.deb
  - cd output && git clone https://github.com/hakimel/reveal.js.git

script:
  - pandoc -t revealjs -s --self-contained slides/SLIDES -V slideNumber=true -o output/index.html -V theme=solarized

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  local_dir: output
  on:
    branch: main
